### PR TITLE
Documentation pass for 1.12.

### PR DESCRIPTION
**Pull request by rosiel**
Thank you for waiting and sorry it took so long. 

Now documented:
* the drush command to update predicates
* batch import for children.

# The intrepid adventuring party
@DiegoPino  @bryjbrown @bondjimbond  and @DonRichards

### CODE REVIEW

**Comment by DiegoPino** [comment]
Sorry folks, I have no time to review. Could anyone other @Islandora/7-x-1-x-committers review? Thanks

**Comment by bryjbrown** [comment]
@rosiel @DiegoPino For some reason Travis is erroring out, but only on the very last test. I'm going to restart Travis to see if we can get it green.

**Review by bryjbrown — APPROVED** [review]

**Comment by bryjbrown** [comment]
Something is going on with Travis that makes it fail on the very last test with Fedora 3.8 (Islandora can't connect to Fedora). I restarted the tests, but I think we'll get the same results. Don't know what to do, but I think someone can at least review the code in the meantime.

**Comment by bryjbrown** [comment]
@rosiel @DiegoPino Travis issues resolved, merging now.

**Pull request merged**
