### PR TITLE
Islandora 1144 - for the release branch

### PR DESCRIPTION
**Pull request by whikloj**

### CODE REVIEW

**Comment by nhart** [comment]
I believe there's an issue with this. 
I have 2 basic image objects linked (A parent with one child). On the child object, I do not see the parent's TN. I only see the "part off" and "manage" bits. 

Perhaps related to this? https://github.com/Islandora/islandora_solution_pack_compound/pull/70/files#diff-b70dff0d0d097b87205025ed79d39ae3R53

**Comment by whikloj** [comment]
That line is to not display the list of children unless a) you are viewing the compound (parent) or there are more than 1 child. ie. Don't display a list of the single child if you are already viewing the single child.

But I think you are right that I didn't include the TN of the parent and just re-used the Part Of text and linked back to the parent.

I'm torn on this, the TN will usually be the same as the first page TN so we will have that displayed twice (for objects with more than 1 child). Not that this is a problem, just wondering if it is extra noise?

Let me know what you think.

**Comment by nhart** [comment]
I guess the issue is if the parent isn't a compound object per se.

In this case, its 2 basic images. The TN would be different.

**Comment by whikloj** [comment]
Fair point, I have written (what I think) is a fix, but I may not get a chance to test it today. Probably have to wait for 1.6

**Pull request closed without merging**
