### PR TITLE
Updated configuration image

### PR DESCRIPTION
**Pull request by rnaughtonwk**
**JIRA Ticket**: (link)

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)

# What does this Pull Request do?

Update the configuration image.  

# What's new?
There is a new option under "Child Relationship predicate" section beginning with " Redirect to first child...." that was not displayed in the documentation.

# Interested parties
@DiegoPino @DonRichards @Islandora/7-x-1-x-committers

### CODE REVIEW

**Review by rosiel — APPROVED** [review]
Ooh, much nicer screenshot. thanks!

**Comment by rosiel** [comment]
Could you set up one for 7.x-dev as well and I'll merge them both?

**Comment by rnaughtonwk** [comment]
Will do.  If you need any other screenshots, I can make them.

**Comment by rnaughtonwk** [comment]
@rosiel I don't see 7.x-dev as an option in the branch menu.

**Comment by rosiel** [comment]
Ooh. My bad. It's the 7.x branch i meant.  🙈

**Comment by rnaughtonwk** [comment]
Sent PR for 7x.

**Comment by rosiel** [comment]
Awesome. Thanks Robin!

**Pull request merged**
