### PR TITLE
Match the function signature.

### PR DESCRIPTION
**Pull request by JojoVes**
**JIRA Ticket**: [ISLANDORA-2041](https://jira.duraspace.org/browse/ISLANDORA-2041) and [ISLANDORA-2040](https://jira.duraspace.org/browse/ISLANDORA-2040)

# What does this Pull Request do?

Makes sure the [function signatures](https://github.com/Islandora/islandora/blob/83a0781e7011f300bbec9cee876b0efaa405e9e2/islandora.api.php#L706) match.

# What's new?
Not much. It should be fairly simple.

# How should this be tested?

Regression test TN derivative creation

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
@JojoVes can you refer to https://jira.duraspace.org/browse/ISLANDORA-2040 in the Pull message ,you can keep both if you want of course? I prefer avoiding duplicated ones to avoid over-counting "fixed bugs" but i'm also ok if you want to have both. Thanks!

**Comment by willtp87** [comment]
Code seems in order.

**Comment by JojoVes** [comment]
@DiegoPino I added that other ticket to the message. :)

**Review by DiegoPino — APPROVED** [review]
Will wait for our conventional 24hrs before merging. The code is good. thanks @JojoVes

**Comment by DiegoPino** [comment]
@JojoVes merged. Thanks for this. closed the tickets also. good work 👍

**Pull request merged**
