### PR TITLE
Replace screenshot for Configuration of islandora_solution_pack_compo…

### PR DESCRIPTION
**Pull request by cdeaneGit**
…und.

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1939?filter=-1

# What does this Pull Request do? 

The image showing how to configure the compound object solution pack does not match what I am seeing in the 7.x-1.9 RC1.

# What's new?
A new screenshot showing current page.

# How should this be tested?
Compare what you see on the screen for Configuration of islandora_solution_pack_compound to the new screen shot.

http://localhost:8000/#overlay=admin/islandora/solution_pack_config/compound_object

# Additional Notes:
N/A

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
@cdeaneGit excellent! Could you please also make an additional Pull request with the same changes against the 7.x-1.9 branch?

**Comment by cdeaneGit** [comment]
When I submitted a pr for 7.x-1.9 there was a conflict because of another pull request for the travis.yml file.  Please do this other pr and then I can submit another pr for 7.x-1.9

**Comment by DiegoPino** [comment]
@cdeaneGit  I don't see any other pull request right now open? But, since 7.x and 7.x-1.9 already diverged you will need to fetch (additionally to this current pull) this 7.x-1.9 branch, create a new branch on your fork based on it (let's name it 7.x-1.9-ISLANDORA-1939) and redo the changes you made here there. And then make a pull request from that branch this 7.x-1.9
That should be the simplest way.

 Also: (more advanced)In case of conflict you have a few options:
A) "rebase" which means bringing the changes, others applied before you, into your local branch and then apply your changes again OR
B) sync your local branch again against the remote 7.x  and apply your changes manually, if needed. Kinda what i explained up there.

In any of those cases, I suggest making a backup of your current branch (the one with the changes you have). It can be sometimes confusing sorry.. just ping me if you need help

https://help.github.com/articles/about-git-rebase/
and
https://help.github.com/articles/syncing-a-fork/

**Comment by DonRichards** [comment]
@DiegoPino Can we ask @MorganDawe to do the same? His [PR](https://github.com/Islandora/islandora_solution_pack_compound/commit/7521a83ebf918a08f6494157adc06386734d2fe4) made a change to `.travis.yml` 7.x branch 2 weeks ago and should have been replicated to the 7.x-1.9 branch. I think this approach makes PRs more approachable by users that might not be proficient with Git but are comfortable with committing documentation. Or are we not wanting 7.x-1.9 to have the Travis update?

**Comment by DiegoPino** [comment]
@DonRichards you mean this one? https://github.com/Islandora/islandora_solution_pack_compound/pull/118 was merged yesterday, not 14 days ago. Also was not originally part of the pre-code-freeze tasks.
We decided (on the call you were part!) to not put any of the ISLANDORA-1880 pull requests into the release because they are 43,  which would mean other 43 additional 7.x-1.9 pulls which don't add any value to final user/ visible part of islandora (in other words, those pulls are for us, devs, not for islandora consumers)

**Comment by cdeaneGit** [comment]
Hi Diego,

I forked Islandora_solution_pack_compound-7.x-1.9-1939   from Islandora_solution_pack_compound-7.x-1.9 (I think)
and reviewed that code and it was different from the first one I forked.

I made another screenshot to match what I am seeing on the screen with the release candidate and the style seen in the readme.

I added this second screen shot inside a comment in the ticket: https://jira.duraspace.org/browse/ISLANDORA-1939?filter=-1

But I am too confused about what I forked down to my repository, so I am making no pull request for this second screenshot.

I think what I really should do is first thing Monday morning scrap everything I forked from Islandora_solution_pack_compound today (both 7.x and 7.x-1.9) and
start over with ONLY Islandora_solution_pack_compound-7.x-1.9 next week.

cheers!
cricket!

**Comment by DonRichards** [comment]
@DiegoPino Sorry, I think I missed understood the decision.

**Review by whikloj — CHANGES_REQUESTED** [review]
Hi @cdeaneGit when you update the 7.x-1.9 branch PR with the revised image @manez request, could you also update this one please.

**Comment by DiegoPino** [comment]
@cdeaneGit @whikloj @manez: not sure hot you want to proceed. First fix what was asked for by @manez in this and the parent #121 pull? Then  make a new one?

Assuming this one and #121 gets fixed with @manez recommendation and then merged, Normally the easiest (less headache) way for the following pull requests is:

1: Simply delete your forked copy and fork again from here: then you will have clean starting point.  Next step.

2. Create a new Branch based on your fork's 7.x called 7.x-updatingthedocs
3. Create a new Branch based on your fork's 7.x-1.9 called 7.x-1.9-updatingthedocs
4. Switch to 7.x-updatingthedocs, make the changes and make a pull request against this REPO, branch 7.x
5. Switch to 7.x-1.9-updatingthedocs, make the changes (again, manually) and make a pull request gainst this REPO, branch 7.x-1.9

If you need help doing this we can walk through this interactively via Skype (just send me an email to dpino@metro.org) with a preferred date/time.

**Comment by whikloj** [comment]
@DiegoPino sorry what is the issue? 

I thought @cdeaneGit was going to add the box highlighting the JAIL checkbox to the image, then update both this (7.x) and #121 (7.x-1.9) pulls? 

Is there something I missed, I did just jump in here.

**Comment by DiegoPino** [comment]
@whikloj  @cdeaneGit said:
>>But I am too confused about what I forked down to my repository, so I am making no pull request for this second screenshot.

**Comment by manez** [comment]
Closing per @cdeaneGit , and awaiting a new one 😄

**Pull request closed without merging**
