### PR TITLE
Update screenshot for jira ticket 1939

### PR DESCRIPTION
**Pull request by cdeaneGit**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1939?filter=-1

# What does this Pull Request do? 

The image showing how to configure the compound object solution pack does not match what I am seeing in the 7.x-1.9 RC1.

# What's new?
A new screenshot showing current page.

# How should this be tested?
Compare what you see on the screen for Configuration of islandora_solution_pack_compound to the new screen shot.

http://localhost:8000/#overlay=admin/islandora/solution_pack_config/compound_object

# Additional Notes:
N/A

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Review by manez — CHANGES_REQUESTED** [review]
@cdeaneGit could you add a block to highlight the JAIL compound block config, as in the old screenshot? The documentation refers to that "as outlined below" which might not be as clear without the highlight.

**Comment by cdeaneGit** [comment]
Hi Melissa,

That was one thing I did want to add to the README.

This was one of the most confusing things about testing compound objects.

The raw OVA comes without JAIL and there are no JAIL config blocks.

Then you put JAIL into $DRUPAL_HOME/sites/all/libraries
and by some mysterious (to me) process process there are JAIL config blocks that need to be displayed.

I will add the screen shot for Jira Ticket 1939.

cheers!
cricket!

**Comment by manez** [comment]
@cdeaneGit that sounds good, but what about the overlay highlighting the JAIL config in this screenshot? Since the documentation refers to that section, I think we either need the overlay on the new screenshot, or change the wording of that  "as outlined below" line.

Edit to add: just to make sure I'm not being confusing, I'm referring to that red square on the old screenshot.

**Comment by cdeaneGit** [comment]
@manez @DiegoPino @whikloj   I have been offline for 3 days.  Thank you all for your comments.   
I am sorry my confusion created work for others.  Diego sent me a 5 step plan about the least confusing way to update the README.md file.

1:      Simply delete your forked copy and fork again from here: then you will have clean starting point. Next step.
2.	Create a new Branch based on your fork's 7.x called 7.x-updatingthedocs
3.	Create a new Branch based on your fork's 7.x-1.9 called 7.x-1.9-updatingthedocs
4.	Switch to 7.x-updatingthedocs, make the changes and make a pull request against this REPO, branch 7.x
5.	Switch to 7.x-1.9-updatingthedocs, make the changes (again, manually) and make a pull request gainst this REPO, branch 7.x-1.9

Since #121 is still open, I would prefer to follow Diego's instructions and then update this ticket to do both changes. 

 If this is not acceptable, I will wait until this ticket is closed and then follow Diego's instructions and make another ticket for the configuration of the BLOCKS that display JAIL related informtation.

Thanks.

**Comment by manez** [comment]
@cdeaneGit I think that if you follow Diego's instructions, it's best if we close this ticket and #121, because odd things will happen when you delete your fork with open pull requests.

**Comment by cdeaneGit** [comment]
@manez @diegoPino @whikloj Melissa, I agree with your statement to close this ticket and then follow Diego's instructions.  I would prefer if you closed the ticket. Thank you.

**Comment by manez** [comment]
@cdeaneGit will do!

**Comment by cdeaneGit** [comment]
compobjblocks_to_configure01

test of display after closing this issue

**Comment by manez** [comment]
@cdeaneGit with the address bar cropped away, that should work nicely.

**Comment by cdeaneGit** [comment]
do not like this jpg.

**Comment by cdeaneGit** [comment]
compobjblocks_to_configure01a

test of dsiplay after closing this issue

**Comment by manez** [comment]
@cdeaneGit it's still a fair amount of real estate, now that I picture it in the context of the readme. How about: 

image

Also, just so we're all on the same page, this is to be added as an additional screenshot? I think the readme still needs an update for the screenshot that's there now, since this is missing some options from the RC VM (there should be Compound Member Query stuff):

image

**Comment by manez** [comment]
@cdeaneGit just FYI, you don't have to post the comment to get the image uploaded. You can paste it, use Preview to see if it looks as you want, and then copy the url git provides, without ever officially posting the comment. It's sneaky, but it works 😄

**Pull request closed without merging**
