### PR TITLE
7.x 1.9 updating the docs

### PR DESCRIPTION
**Pull request by cdeaneGit**
**JIRA Ticket**: (https://jira.duraspace.org/browse/ISLANDORA-1939)

* Other Relevant Links (none)

# What does this Pull Request do? Revise README.md 

A brief description of what the intended result of the PR will be and/or what problem it solves.

1.  In the Configuration section:  Revise screenshot of Configuration form to show the Compound Member Query 

section at the bottom.

2.  In the Block section: Revise text.
	Replace "There exists two block options"
	With    "There exist two block options"
	Because options is plural.

# What's new?
1.  Add screenshot from Block Configuration page to show the two Blocks for Compound Object Navigation 

# How should this be tested?
   View the README.md file.

# Interested parties
Tag (@Islandora/7-x-1-x-committers)

### CODE REVIEW

**Comment by manez** [comment]
@cdeaneGit you'll need to redo this pull and have it target the 7.x-1.9 branch. Right now both of your pull requests are targeting the main branch.

**Comment by cdeaneGit** [comment]
Resubmitted.

**Comment by DiegoPino** [comment]
@cdeaneGit feel free to close this one since you made the other one (thanks). If you want me to close it instead, np!

**Comment by cdeaneGit** [comment]
Replace with 
https://github.com/Islandora/islandora_solution_pack_compound/pull/124

**Pull request closed without merging**
